import {iJWTPayload} from "@customTypes/authTypes";

declare module "express-serve-static-core" {
	/*
		NOTE: The naming-convention rule has been disabled for this line because
		Request is part of @types/express and can't be renamed to
		iRequest
	 */
	// eslint-disable-next-line @typescript-eslint/naming-convention
	interface Request {
		/**
		 * Unique request ID generated by the middleware.
		 */
		uniqueRequestId: string;

		decodedAccessToken: iJWTPayload;
	}
}
